spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate.default_batch_fetch_size: 100
---
spring.config.activate.on-profile: local
spring:
  jpa:
    properties:
      hibernate:
  #        format_sql: true
  #        show_sql: true

  flyway:
    clean-on-validation-error: true
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
---
spring.config.activate.on-profile: local-dev
spring:
  jmx:
    enabled: false
  docker:
    compose:
      enabled: true
  flyway:
    enabled: false
    validate-on-migrate: false
storage:
  datasource:
    core:
      jdbc-url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 8
        minimum-idle: 5
        idle-timeout: 300000
        connection-timeout: 20000
        validation-timeout: 5000